'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программой.
'     Исполняемая версия:4.0.30319.42000
'
'     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
'     повторной генерации кода.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Public NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Функция автоматического сохранения My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("admin")>  _
        Public Property rt_6M6A__PMP8G_Es2cT() As String
            Get
                Return CType(Me("rt_6M6A__PMP8G_Es2cT"),String)
            End Get
            Set
                Me("rt_6M6A__PMP8G_Es2cT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("admin")>  _
        Public Property w_4HD_w5Fqkv6ref_Kq() As String
            Get
                Return CType(Me("w_4HD_w5Fqkv6ref_Kq"),String)
            End Get
            Set
                Me("w_4HD_w5Fqkv6ref_Kq") = value
            End Set
        End Property
        
        '''<summary>
        '''user1
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("user1"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property xZeyZSDtZ_M8PpJCn() As Integer
            Get
                Return CType(Me("xZeyZSDtZ_M8PpJCn"),Integer)
            End Get
            Set
                Me("xZeyZSDtZ_M8PpJCn") = value
            End Set
        End Property
        
        '''<summary>
        '''user2
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("user2"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property y6X6eyNr_ZGNgPK2M() As Integer
            Get
                Return CType(Me("y6X6eyNr_ZGNgPK2M"),Integer)
            End Get
            Set
                Me("y6X6eyNr_ZGNgPK2M") = value
            End Set
        End Property
        
        '''<summary>
        '''user3
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("user3"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property W84Ammg_gcy__LhxKja() As Integer
            Get
                Return CType(Me("W84Ammg_gcy__LhxKja"),Integer)
            End Get
            Set
                Me("W84Ammg_gcy__LhxKja") = value
            End Set
        End Property
        
        '''<summary>
        '''user4
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("user4"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property JVJtJ4z_A9V3FnwmS() As Integer
            Get
                Return CType(Me("JVJtJ4z_A9V3FnwmS"),Integer)
            End Get
            Set
                Me("JVJtJ4z_A9V3FnwmS") = value
            End Set
        End Property
        
        '''<summary>
        '''user5
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("user5"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property y7pZ9AWbPxx_Cy_28X() As Integer
            Get
                Return CType(Me("y7pZ9AWbPxx_Cy_28X"),Integer)
            End Get
            Set
                Me("y7pZ9AWbPxx_Cy_28X") = value
            End Set
        End Property
        
        '''<summary>
        '''user6
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("user6"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property xcwsG_2Pga_sEtwzcj() As Integer
            Get
                Return CType(Me("xcwsG_2Pga_sEtwzcj"),Integer)
            End Get
            Set
                Me("xcwsG_2Pga_sEtwzcj") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property name1() As String
            Get
                Return CType(Me("name1"),String)
            End Get
            Set
                Me("name1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property name2() As String
            Get
                Return CType(Me("name2"),String)
            End Get
            Set
                Me("name2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property name3() As String
            Get
                Return CType(Me("name3"),String)
            End Get
            Set
                Me("name3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property name4() As String
            Get
                Return CType(Me("name4"),String)
            End Get
            Set
                Me("name4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property name5() As String
            Get
                Return CType(Me("name5"),String)
            End Get
            Set
                Me("name5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property name6() As String
            Get
                Return CType(Me("name6"),String)
            End Get
            Set
                Me("name6") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.finance_menu.My.MySettings
            Get
                Return Global.finance_menu.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
